### ISSUE TITLE
How to start the policy net?

### ISSUE THREAD

**Issue by as0770** [johnhuang-cn/FancyBing#1]
Hi,

thanks for sharing this project!

In the start policy net .bat the command is obviously wrong:

`java -ms4000m -mx4000m -jar fancybing-mcts-1.0-bin.jar`

If I try

` java -ms4000m -mx4000m -jar fancybing-policynet-1.0-bin.jar`

or just 

` java -jar fancybing-policynet-1.0-bin.jar`

I get this error message:

`o.n.l.f.Nd4jBackend - Loaded [JCublasBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 32
Exception in thread "main" java.lang.ExceptionInInitializerError
	at net.xdevelop.go.policynet.PolicyNetService.main(PolicyNetService.java:74)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6212)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6188)
	... 3 more
Caused by: java.lang.UnsatisfiedLinkError: no jnicusolver in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
	at org.bytedeco.javacpp.Loader.load(Loader.java:777)
	at org.bytedeco.javacpp.Loader.load(Loader.java:684)
	at org.bytedeco.javacpp.cusolver.<clinit>(cusolver.java:14)
	at org.nd4j.jita.allocator.context.impl.BasicContextPool.createNewSolverHandle(BasicContextPool.java:203)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool.fillPoolWithResources(LimitedContextPool.java:91)
	at org.nd4j.jita.allocator.context.impl.LimitedContextPool.<init>(LimitedContextPool.java:56)
	at org.nd4j.jita.handler.impl.CudaZeroHandler.<init>(CudaZeroHandler.java:131)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<init>(AtomicAllocator.java:128)
	at org.nd4j.jita.allocator.impl.AtomicAllocator.<clinit>(AtomicAllocator.java:74)
	at org.nd4j.linalg.jcublas.JCublasNDArrayFactory.<init>(JCublasNDArrayFactory.java:86)
	... 8 more
Caused by: java.lang.UnsatisfiedLinkError: /home/alex/.javacpp/cache/fancybing-policynet-1.0-bin.jar/org/bytedeco/javacpp/linux-x86_64/libjnicusolver.so: libcusolver.so.8.0: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:956)
	... 18 more
`

I guess the command line options are also wrong...

I am on Ubuntu 16.04.

**Comment by johnhuang-cn** [comment]
I only tested in Win64, it seems caused by native library loading issue.
Maybe you needs re-compile and package them in linux.

Thanks,
John Huang

2018-04-20 0:08 GMT+08:00 as0770 <notifications@github.com>:

**Comment by as0770** [comment]
Unfortunately I am not able to compile it, I am not familiar with java. I'll wait until someone else with Linux comes along :)
